Repository TEAM-PLAYTOGETHER/PlayTogether_Android, pull requests merged in 2022-05, with the labels that each got.

#32 [FEAT] #21 - 신청완료뷰 완료(어댑터는 안만듬)
  .idea/discord.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderAppliedActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/VerticalItemDecoration.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/res/drawable/ic_icn_clear.xml
  app/src/main/res/drawable/line_dotted_black.xml
  app/src/main/res/drawable/rectangle_fill_gray04_border_black01_radius_10.xml
  app/src/main/res/layout/activity_applied.xml
  app/src/main/res/layout/activity_apply_thunder_detail.xml
  app/src/main/res/layout/activity_thunder_applied.xml
  app/src/main/res/layout/item_members.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#34 [FEAT] #33 - 쪽지함 뷰 완성(어댑터는 안만듬)
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/res/drawable/circle_main_green.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_message_room.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#36 [FEAT] #35- 채팅창 레이아웃 완성
  .idea/misc.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/InChattingFragment.kt
  app/src/main/res/drawable/ic_icn_message.xml
  app/src/main/res/drawable/rectangle_radius_10.xml
  app/src/main/res/layout/fragment_in_chatting.xml
  app/src/main/res/layout/item_message_room.xml
  app/src/main/res/layout/item_my_chat.xml
  app/src/main/res/layout/item_other_chat.xml
  app/src/main/res/values/colors.xml
  build.gradle.kts
Labels: 🌈Feature, 🍏용민🍏

#37 Feature/5 home fragment
  .idea/jarRepositories.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_group_8925.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/img_temp.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_hot.xml
  app/src/main/res/layout/item_home_new.xml
  app/src/main/res/raw/plto_refresh.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
Labels: 🌈Feature, 🍇종찬🍇

#39 [FEAT] #31 sign in branch processing
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignViewModel.kt
  app/src/main/res/drawable-hdpi/ic_icn_check.png
  app/src/main/res/drawable-hdpi/selector_rectangle_fill_gray02_to_fill_green.xml
  app/src/main/res/drawable-hdpi/selector_text_gray01_to_black01.xml
  app/src/main/res/drawable-mdpi/ic_icn_check.png
  app/src/main/res/drawable-mdpi/selector_rectangle_border_gray03_to_black02.xml
  app/src/main/res/drawable-xhdpi/ic_icn_check.png
  app/src/main/res/drawable-xxhdpi/ic_icn_check.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_check.png
  app/src/main/res/drawable/rectangle_boarder_gray_black02_radius_10.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/item_message_room.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#43 [FEAT] #42 onboarding join open
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SecondOnboardingActivity.kt
  app/src/main/res/drawable-hdpi/selector_text_gray01_to_white.xml
  app/src/main/res/layout/activity_second_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#45 [CHORE] #44 - module test
  PlayTogether-Android.zip
Labels: 🌈Feature, 🍑혜빈🍑

#48 [FEAT] #47 onboarding join
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/FirstOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SecondOnboardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/onBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/res/drawable-hdpi/ic_icn_calendar.png
  app/src/main/res/drawable-mdpi/ic_icn_calendar.png
  app/src/main/res/drawable-xhdpi/ic_icn_calendar.png
  app/src/main/res/drawable-xxhdpi/ic_icn_calendar.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_calendar.png
  app/src/main/res/layout/activity_first_on_boarding.xml
  app/src/main/res/layout/activity_join_on_boarding.xml
  app/src/main/res/layout/activity_second_onboarding.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_info.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#50 [FEAT] #49 id duplication server
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/ApiModule.kt
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/AuthInterceptor.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/dialog_one_question.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/api/sign/SignService.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignId.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResponseSignId.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/IdDuplicationCheckData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/IdDuplicationCheckItem.kt
  domain/src/main/java/com/playtogether_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignIdUseCase.kt
Labels: 🌈Feature, 🍑혜빈🍑

#53 [FEAT] #52 - mypage view end
  .idea/misc.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#56 [FEAT] #55 change icon
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/res/drawable-hdpi/ic_icn_chat_active.png
  app/src/main/res/drawable-hdpi/ic_icn_chat_inactive.png
  app/src/main/res/drawable-hdpi/ic_icn_home_active.png
  app/src/main/res/drawable-hdpi/ic_icn_home_inactive.png
  app/src/main/res/drawable-hdpi/ic_icn_mypage_inactive.png
  app/src/main/res/drawable-hdpi/ic_icn_thun_active.png
  app/src/main/res/drawable-hdpi/ic_icn_thun_inactive.png
  app/src/main/res/drawable-mdpi/ic_icn_chat_active.png
  app/src/main/res/drawable-mdpi/ic_icn_chat_inactive.png
  app/src/main/res/drawable-mdpi/ic_icn_home_active.png
  app/src/main/res/drawable-mdpi/ic_icn_home_inactive.png
  app/src/main/res/drawable-mdpi/ic_icn_mypage_inactive.png
  app/src/main/res/drawable-mdpi/ic_icn_thun_active.png
  app/src/main/res/drawable-mdpi/ic_icn_thun_inactive.png
  app/src/main/res/drawable-xhdpi/ic_icn_chat_active.png
  app/src/main/res/drawable-xhdpi/ic_icn_chat_inactive.png
  app/src/main/res/drawable-xhdpi/ic_icn_home_active.png
  app/src/main/res/drawable-xhdpi/ic_icn_home_inactive.png
  app/src/main/res/drawable-xhdpi/ic_icn_mypage_active.png
  app/src/main/res/drawable-xhdpi/ic_icn_mypage_inactive.png
  app/src/main/res/drawable-xhdpi/ic_icn_thun_active.png
  app/src/main/res/drawable-xhdpi/ic_icn_thun_inactive.png
  app/src/main/res/drawable-xhdpi/ic_main_logo.png
  app/src/main/res/drawable-xhdpi/selector_bottom_navi_icon_chat.xml
  app/src/main/res/drawable-xhdpi/selector_bottom_navi_icon_mypage.xml
  app/src/main/res/drawable-xhdpi/selector_bottom_navi_icon_thunder.xml
  app/src/main/res/drawable-xxhdpi/ic_icn_chat_active.png
  app/src/main/res/drawable-xxhdpi/ic_icn_chat_inactive.png
  app/src/main/res/drawable-xxhdpi/ic_icn_home_active.png
  app/src/main/res/drawable-xxhdpi/ic_icn_home_inactive.png
  app/src/main/res/drawable-xxhdpi/ic_icn_mypage_inactive.png
  app/src/main/res/drawable-xxhdpi/ic_icn_thun_active.png
  app/src/main/res/drawable-xxhdpi/ic_icn_thun_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_chat_active.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_chat_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_home_active.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_home_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_mypage_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_thun_active.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_thun_inactive.png
  app/src/main/res/drawable/selector_bottom_navi_icon_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  data/src/main/AndroidManifest.xml
  domain/src/main/AndroidManifest.xml
Labels: 🌈Feature, 🍑혜빈🍑

#59 [FEAT] #57 signup server connection
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/layout/activity_sign_up_info.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignUpItem.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignIdUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignUpUseCaes.kt
Labels: 🌈Feature, 🍑혜빈🍑

#63 #[FEAT] #60 sign in server connection
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/layout/dialog_one_question.xml
  data/src/main/java/com/playtogether_android/data/api/sign/SignService.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignIn.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResponseSignIn.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignInData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignInItem.kt
  domain/src/main/java/com/playtogether_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignInUseCase.kt
Labels: 🌈Feature, 🍑혜빈🍑

#67 Feat/66 jwt token connection
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/playtogether_android/app/di/ApiModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/AuthInterceptor.kt
  app/src/main/java/com/playtogether_android/app/util/PlayTogetherSharedPreference.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
Labels: 🌈Feature, 🍑혜빈🍑

#72 Feat/62 writing logic
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🌈Feature, 🍏용민🍏

#75 Feature/38 thunder list
  .gitignore
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/base/BaseBottomDialogFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/temp/TempData.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragmentDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/SortDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/BindingAdapter.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/drawable/ic_icn_gray_exit.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_previous.xml
  app/src/main/res/drawable/ic_rectangle_category_button.xml
  app/src/main/res/drawable/ic_show.xml
  app/src/main/res/drawable/ic_underline.xml
  app/src/main/res/drawable/icn_before_false.xml
  app/src/main/res/drawable/icn_before_true.xml
  app/src/main/res/drawable/icn_next_false.xml
  app/src/main/res/drawable/icn_next_true.xml
  app/src/main/res/drawable/rectangle_fill_gray_black02_radius_14.xml
  app/src/main/res/drawable/rectangle_fill_white_left_right_radius_20.xml
  app/src/main/res/layout/activity_thunder_list.xml
  app/src/main/res/layout/dialog_sort.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_dialog.xml
  app/src/main/res/layout/item_home_hot.xml
  app/src/main/res/layout/item_home_new.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/com/playtogether_android/data/api/light/LightService.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/light/LightMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseLightListCategory.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/light/LightRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/light/LightRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetThunderCategoryUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#77 [FEAT] #73 modify view
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/FirstOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_first_on_boarding.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_my_page.xml
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignInData.kt
Labels: 🌈Feature, 🍑혜빈🍑

#86 Feature/83 apply thunder detail post submit
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  data/src/main/java/com/playtogether_android/data/api/light/LightService.kt
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderService.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseLightJoinCancel.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResponseThunderJoinCancel.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderJoinCancel.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostThunderJoinCancelUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#89 [FEAT] #78 message server connection
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/FirstOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/item_message_room.xml
  data/src/main/java/com/playtogether_android/data/mapper/message/MessageMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/message/ResponseMessageData.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/MessageRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/MessageData.kt
Labels: 🌈Feature, 🍑혜빈🍑

#94 [FEAT] #93 - first onboarding name
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/FirstOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/layout/activity_first_on_boarding.xml
Labels: 🌈Feature, 🍑혜빈🍑

#95 [FEAT] #92 - 채팅 서버 연결 성공
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChatAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChatAdapter2.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChatViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/SendMessageViewModel.kt
  data/src/main/java/com/playtogether_android/data/api/message/ChatService.kt
  data/src/main/java/com/playtogether_android/data/api/message/MessageSendService.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/SendMessageDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/SendMessageDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/message/ChatMapper.kt
  data/src/main/java/com/playtogether_android/data/mapper/message/SendMessageMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/message/RequestMessageSend.kt
  data/src/main/java/com/playtogether_android/data/model/response/message/ResponseChatData.kt
  data/src/main/java/com/playtogether_android/data/model/response/message/ResponseMessageSend.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/ChatRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/SendMessageRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/ChatData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/GetSendMessageData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/PostSendMessageData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/ChatRepository.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/MessageSendReposiotry.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/GetChatUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/PostSendMessageUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#97 Feat/96 add splash
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/res/drawable-hdpi/ic_logo.png
  app/src/main/res/drawable-mdpi/ic_logo.png
  app/src/main/res/drawable-xhdpi/ic_logo.png
  app/src/main/res/drawable-xxhdpi/ic_logo.png
  app/src/main/res/drawable-xxxhdpi/ic_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: 🌈Feature, 🍑혜빈🍑

#99 Feature/90 apply thunder detail server
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplicantListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/OpenThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabApplyFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabLikeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabOpenFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/res/layout/activity_apply_thunder_detail.xml
  app/src/main/res/layout/activity_open_thunder_detail.xml
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/item_thunder_applicant_list.xml
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderDetailData.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderTabListData.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/Member.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/Organizer.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderDetailData.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderJoinCancelData.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderTabListData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/GetThunderDetailMemberUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/GetThunderDetailOrganizerUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/GetThunderDetailUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostThunderJoinCancelUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#104 [FEAT] : #90 - lightId : String -> lightId : Int
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseLightListCategory.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
Labels: 🐞Fix, 🍇종찬🍇

#105 Feat/98 move other mypag
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/OthersMyPageActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/viewModel/MyPageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/res/layout/activity_others_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/mypage/MyPageMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/mypage/ResponseUserCheck.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/mypage/UserCheckData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/mypage/MyPageRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/mypage/GetUserCheckUseCase.kt
Labels: 🌈Feature, 🍑혜빈🍑

#107 Feat/106 apply thunder server connection
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/OthersMyPageActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/viewModel/MyPageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/res/drawable-hdpi/icn_mypage_active.png
  app/src/main/res/drawable-mdpi/icn_mypage_active.png
  app/src/main/res/drawable-xhdpi/ic_plto_logo.png
  app/src/main/res/drawable-xhdpi/icn_mypage_active.png
  app/src/main/res/drawable-xhdpi/selector_bottom_navi_icon_mypage.xml
  app/src/main/res/drawable-xxhdpi/icn_mypage_active.png
  app/src/main/res/drawable-xxxhdpi/icn_mypage_active.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  data/src/main/java/com/playtogether_android/data/api/home/HomeService.kt
  data/src/main/java/com/playtogether_android/data/datasource/home/HomeDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/home/HomeDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/home/HomeMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/home/ResponseJoinThunder.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/home/HomeRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/home/JoinThunderData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/home/HomeRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/home/PostJoinThunderUseCase.kt
Labels: 🌈Feature, 🍑혜빈🍑

#110 [FEAT] : #5 - 새로고침 뷰 기능 구현
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🌈Feature, 🍇종찬🍇

#112 Feat/100 writing server
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/di/NetworkModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/di/UseCaseModule.kt
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderCreateService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderCreateMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/thunder/RequestThunderCreate.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResponseThunderCreate.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/SendMessageRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderCreateRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/GetThunderCreateData.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/PostThunderCreateData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderCreateRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostThunderCreateUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#113 [FEAT] #100 - 글쓰기 뷰 서버 연결 ( pull 받음 )
  app/src/main/java/com/playtogether_android/app/di/ViewModelModule.kt
Labels: 🌈Feature, 🍏용민🍏

#122 Fix/111 test branch
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderAppliedActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/OpenThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/drawable/img_do_list.png
  app/src/main/res/drawable/img_eat_list.png
  app/src/main/res/drawable/img_go_list.png
  app/src/main/res/layout/activity_apply_thunder_detail.xml
  app/src/main/res/layout/activity_open_thunder_detail.xml
  app/src/main/res/layout/activity_thunder_applied.xml
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/item_thunder_list.xml
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderTabListData.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderTabListData.kt
Labels: 🌈Feature, 🍇종찬🍇

#124 Fix/test branch
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/OthersMyPageActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/OpenThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/drawable-hdpi/ic_icn_edit.png
  app/src/main/res/drawable-hdpi/icn_setting.png
  app/src/main/res/drawable-mdpi/ic_icn_edit.png
  app/src/main/res/drawable-mdpi/icn_setting.png
  app/src/main/res/drawable-xhdpi/ic_icn_edit.png
  app/src/main/res/drawable-xhdpi/icn_setting.png
  app/src/main/res/drawable-xxhdpi/ic_icn_edit.png
  app/src/main/res/drawable-xxhdpi/icn_setting.png
  app/src/main/res/drawable-xxxhdpi/icn_edit.png
  app/src/main/res/drawable-xxxhdpi/icn_setting.png
  app/src/main/res/layout/activity_others_my_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/com/playtogether_android/data/mapper/mypage/MyPageMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/mypage/ResponseUserCheck.kt
  domain/src/main/java/com/playtogether_android/domain/model/mypage/UserCheckData.kt
Labels: 🛠Chore, 🍇종찬🍇

#127 Modify/120 modify server code
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
Labels: 🛠Chore, 🍑혜빈🍑

#133 [FEAT] modify mbti type
  app/src/main/java/com/playtogether_android/app/util/PlayTogetherSharedPreference.kt
  data/src/main/java/com/playtogether_android/data/model/response/mypage/ResponseUserCheck.kt
  domain/src/main/java/com/playtogether_android/domain/model/mypage/UserCheckData.kt
Labels: 🍑혜빈🍑

#134 [FIX] #130 chat size control
  app/src/main/res/layout/item_my_chat.xml
  app/src/main/res/layout/item_other_chat.xml
Labels: 🌈Feature, 🍏용민🍏
