Repository TEAM-PLAYTOGETHER/PlayTogether_Android, pull requests merged in 2022-04, with the labels that each got.

#7 [Chore] #6 modify setting code
  app/src/main/java/com/playtogether_android/app/presentation/base/BaseActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/base/BaseFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛠Chore, 🍑혜빈🍑

#9 Feat/8 createthunder layout
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/res/drawable/ic_icn_back.xml
  app/src/main/res/drawable/ic_icn_camera.xml
  app/src/main/res/drawable/ic_icn_check_active.xml
  app/src/main/res/drawable/ic_icn_check_inactive.xml
  app/src/main/res/drawable/ic_img_do_active.xml
  app/src/main/res/drawable/ic_img_do_inactive.xml
  app/src/main/res/drawable/ic_img_eat_active.xml
  app/src/main/res/drawable/ic_img_eat_inactive.xml
  app/src/main/res/drawable/ic_img_go_active.xml
  app/src/main/res/drawable/ic_img_go_inactive.xml
  app/src/main/res/drawable/rectangle_border_dotted_gray02_radius_10.xml
  app/src/main/res/drawable/rectangle_border_gray03_radius_10.xml
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#11 [CHORE] #10 modify httplogging
  .idea/jarRepositories.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛠Chore, 🍑혜빈🍑

#13 [Feat1#2 login layout
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/res/drawable/rectangle_border_gray01_radius_10.xml
  app/src/main/res/drawable/rectangle_border_gray03_radius_10dp.xml
  app/src/main/res/drawable/rectangle_fill_gray03_10dp.xml
  app/src/main/res/drawable/rectangle_fill_gray_black_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_grayadadad_radius_0.xml
  app/src/main/res/drawable/selector_rectangle_border_gray03_to_gray01.xml
  app/src/main/res/drawable/selector_rectangle_fill_gray03_to_black.xml
  app/src/main/res/drawable/selector_text_gray01_to_main_green.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🌈Feature, 🍑혜빈🍑

#17 [FEAT] #16 - 상세보기 디폴트 뷰 레이아웃 완성
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/res/drawable/ic_icn_like_default.xml
  app/src/main/res/drawable/ic_icn_like_filled.xml
  app/src/main/res/drawable/ic_img_profile.xml
  app/src/main/res/drawable/line_dotted_white.xml
  app/src/main/res/drawable/rectangle_border_black02_radius_14.xml
  app/src/main/res/drawable/rectangle_fill_green_border_black_radius_10.xml
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#20 [FEAT] #18 - 커스텀 다이얼로그 완성
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/AppliedActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/drawable/inset_horizontal_58.xml
  app/src/main/res/drawable/rectangle_fill_black02_radius_14.xml
  app/src/main/res/drawable/rectangle_fill_white_border_black01_radius10.xml
  app/src/main/res/layout/activity_applied.xml
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/dialog_yes_no.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#24 [FEAT] #23 signup idpw layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/res/drawable-hdpi/rectangle_fill_gray03_radius_5.xml
  app/src/main/res/drawable-hdpi/selector_rectangle_fill_gray03_to_black01.xml
  app/src/main/res/drawable/rectangle_fill_black01_radius_5.xml
  app/src/main/res/layout/activity_sign_up_info.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#26 [FEAT] #25 signup finish
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpFinishActivity.kt
  app/src/main/res/drawable-hdpi/ic_icn_exit.png
  app/src/main/res/drawable-hdpi/ic_main_img.png
  app/src/main/res/drawable-mdpi/ic_icn_exit.png
  app/src/main/res/drawable-mdpi/ic_main_img.png
  app/src/main/res/drawable-xhdpi/ic_icn_exit.png
  app/src/main/res/drawable-xhdpi/ic_main_img.png
  app/src/main/res/drawable-xxhdpi/ic_icn_exit.png
  app/src/main/res/drawable-xxhdpi/ic_main_img.png
  app/src/main/res/drawable-xxxhdpi/ic_icn_exit.png
  app/src/main/res/drawable-xxxhdpi/ic_main_img.png
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#30 [FEAT] #28 onboarding mbti
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/FirstOnBoardingActivity.kt
  app/src/main/res/drawable-mdpi/rectangle_fill_gray03_border_gray02_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_black01_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_gray3_radius_0.xml
  app/src/main/res/drawable/rectangle_fill_green_radius_0.xml
  app/src/main/res/drawable/selector_rectangle_gray01_to_black01_check.xml
  app/src/main/res/drawable/selector_text_gray01_to_main_green_check.xml
  app/src/main/res/layout/activity_first_on_boarding.xml
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑
