Repository TEAM-PLAYTOGETHER/PlayTogether_Android, pull requests merged in 2022-10, with the labels that each got.

#265 Modify/262 resolve profile null
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SelectOnboardingActivity.kt
Labels: 🛠Chore, 🍑혜빈🍑

#266 [QA] QA 반영 2차
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginTermsActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/viewmodel/GoogleLoginRepository.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabApplyFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabLikeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/TabOpenFragment.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/drawable/ic_group_popup.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignup.kt
Labels: 🍇종찬🍇

#271 Chore/270 reflect qa
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SelectOnboardingActivity.kt
  app/src/main/res/drawable-xxxhdpi/rectangle_fill_green_down_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_white_black_stroke.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_on_boarding_introduce.xml
  app/src/main/res/layout/dialog_one_question.xml
Labels: 🛠Chore, 🍑혜빈🍑

#278 Feat/yongmin qa
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChatAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChatViewHolder.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChattingAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChattingData.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChattingViewHolder.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/MessageAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/VerticalItemDecoration.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/request/ReqEnterRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/request/ReqSendMessage.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/SocketSingleton.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/WebSocketListener.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/request/ReqEnterRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/request/ReqSendMessage.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/response/NewMessageReceived.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/response/ResConnection.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/response/ResEnterRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/response/ResExitRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/response/ResSendMessage.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChatViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChattingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/MessageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListItemAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/ChatDateStringFormat.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/drawable/rectangle_radius_20.xml
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/item_chat_date.xml
  app/src/main/res/layout/item_chat_loading.xml
  app/src/main/res/layout/item_search_thunder_list.xml
  app/src/main/res/layout/item_thunder_list.xml
  data/src/main/java/com/playtogether_android/data/api/message/ChatService.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/ChatRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/ChatRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/GetChatUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#279 [QA] QA반영 및 접근 권한 util로 뺌
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/util/GalleryUtil.kt
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/layout/activity_thunder_detail.xml
Labels: 🍇종찬🍇

#282 Chore/281 add lottie
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/MyInfoFragment.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/plto_splash.json
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: 🛠Chore, 🍑혜빈🍑

#284 Feat/yongmin qa
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChatAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChatViewHolder.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChattingAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/ChattingViewHolder.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/adapter/VerticalItemDecoration.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/ChattingSocket.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/socketData/SocketSingleton.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChatViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChattingViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/BindingAdapter.kt
  app/src/main/java/com/playtogether_android/app/util/ChatDateStringFormat.kt
  app/src/main/java/com/playtogether_android/app/util/ChattingFormatter.kt
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/item_chat_date.xml
  app/src/main/res/layout/item_my_chat.xml
  app/src/main/res/layout/item_other_chat.xml
  app/src/main/res/values/colors.xml
  data/src/main/java/com/playtogether_android/data/api/message/ChatService.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/ChatDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/message/ChatMapper.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/ChatRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/ChatData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/ChattingData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/ChatRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/GetChatUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#285 Feat/yongmin qa
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChattingViewModel.kt
Labels: 🐞Fix, 🍏용민🍏

#287 Chore/286 modify profile subway
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/EditProfileActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/MyInfoFragment.kt
Labels: 🐞Fix, 🛠Chore, 🍑혜빈🍑
