Repository TEAM-PLAYTOGETHER/PlayTogether_Android, pull requests merged in 2022-08, with the labels that each got.

#161 [FEAT] hot/new list 구현 (닫힌 번개, 열린 번개 구분 아직 미완)
  .idea/jarRepositories.xml
  app/.idea/gradle.xml
  app/.idea/misc.xml
  app/.idea/modules.xml
  app/.idea/vcs.xml
  app/.idea/workspace.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/res/drawable-hdpi/icn_like_unfilled.png
  app/src/main/res/drawable-mdpi/icn_like_unfilled.png
  app/src/main/res/drawable-xhdpi/icn_like_unfilled.png
  app/src/main/res/drawable/ic_btn_google.xml
  app/src/main/res/drawable/ic_btn_kakao.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_hot.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  data/src/main/java/com/playtogether_android/data/api/light/LightService.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/light/LightMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseHomeLightning.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/light/LightRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/HomeLightningData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/light/LightRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetHotListUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetNewListUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#162 [ REFACTOR] 먹/갈/할 리스트 정렬 인원순 -> 찜 많은순
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/SortDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/SpaceItemDecoration.kt
  app/src/main/res/drawable/ic_icn_like_filled.xml
  app/src/main/res/layout/activity_thunder_list.xml
  app/src/main/res/layout/dialog_sort.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/mapper/light/LightMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseLightListCategory.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
Labels: 🛠Chore, 🍇종찬🍇

#167 [FEAT] #164 - add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🌈Feature, 🍑혜빈🍑

#165 [FEAT] : kakao,google api 없는 깡통 로그인 연결
  .idea/jarRepositories.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderAppliedActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/temp/TempData.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ThunderListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListItemAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/res/drawable/ic_icn_like_unfilled.xml
  app/src/main/res/layout/activity_thunder_list.xml
  app/src/main/res/layout/fragment_thunder_do.xml
  app/src/main/res/layout/fragment_thunder_eat.xml
  app/src/main/res/layout/fragment_thunder_go.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  data/src/main/java/com/playtogether_android/data/mapper/light/LightMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseLightListCategory.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/light/LightRepository.kt
Labels: 🌈Feature, 🍇종찬🍇

#172 [FEAT] 사진가져오기 3장, 카메라 권한 설정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/adapter/CreateThunderPhotoListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListItemAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/BindingAdapter.kt
  app/src/main/java/com/playtogether_android/app/util/ListComparator.kt
  app/src/main/java/com/playtogether_android/app/util/SpaceItemDecoration.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/layout/fragment_thunder_eat.xml
  app/src/main/res/layout/item_create_thunder_photo.xml
  data/src/main/java/com/playtogether_android/data/mapper/light/LightMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/light/ResponseHomeLightning.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/light/LightRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/CategoryData.kt
  domain/src/main/java/com/playtogether_android/domain/model/light/HomeLightningData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/light/LightRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetHotListUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetNewListUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#173 Feat/169 subway chip
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/adapter/SubwayAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/util/BindingAdapter.kt
  app/src/main/res/drawable-xhdpi/rectangle_fill_black01_radius_50.xml
  app/src/main/res/drawable-xxxhdpi/selector_text_gray01_to_gray03.xml
  app/src/main/res/layout/activity_on_boarding_introduce.xml
  app/src/main/res/layout/activity_search_subway.xml
  app/src/main/res/layout/item_subway_select_chip.xml
  app/src/main/res/values/strings.xml
  data/build.gradle.kts
  domain/build.gradle.kts
Labels: 🌈Feature, 🍑혜빈🍑

#170 Feat/142 chatting
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChatAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/WebSocketListener.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/SendMessageSocket.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/SubscribeSocket.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChatViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/SendMessageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/OthersMyPageActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/viewModel/MyPageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplyThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/java/com/playtogether_android/app/testdi/ApiModule.kt
  app/src/main/java/com/playtogether_android/app/testdi/DataSourceModule.kt
  app/src/main/java/com/playtogether_android/app/testdi/RepositoryModule.kt
  app/src/main/res/layout/activity_chatting.xml
  data/src/main/java/com/playtogether_android/data/api/message/MessageSendService.kt
  data/src/main/java/com/playtogether_android/data/api/message/RoomIdService.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/SendMessageDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/message/SendMessageDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/message/SendMessageMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/message/RequestMessageSend.kt
  data/src/main/java/com/playtogether_android/data/model/response/message/ResponseMessageSend.kt
  data/src/main/java/com/playtogether_android/data/model/response/message/ResponseRoomIdData.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/RoomIdRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/message/SendMessageRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/ChatData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/GetSendMessageData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/PostSendMessageData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/RoomIdData.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/SocketChatData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/MessageSendReposiotry.kt
  domain/src/main/java/com/playtogether_android/domain/repository/message/RoomIdRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/GetRoomIdUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/message/PostSendMessageUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#179 Feat/178 onboarding redownload
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/adapter/OnboardingReDownAdapter.kt
  app/src/main/java/com/playtogether_android/app/util/BindingAdapter.kt
  app/src/main/res/layout/activity_onboarding_re_down_load.xml
  app/src/main/res/layout/item_redown_onboarding_list.xml
Labels: 🌈Feature, 🍑혜빈🍑

#186 Feat/184 mypage setting view
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/WebViewActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/res/layout/activity_my_page_setting.xml
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: 🌈Feature, 🍑혜빈🍑

#181 [REFACTOR] 최신/찜순 bottomSheet -> tablayout
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeDialogAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragmentDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListItemAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/testdi/PlayTogetherApplication.kt
  app/src/main/java/com/playtogether_android/app/util/FirebaseMessagingServiceUtil.kt
  app/src/main/java/com/playtogether_android/app/util/ListAdapterComparator.kt
  app/src/main/java/com/playtogether_android/app/util/ListComparator.kt
  app/src/main/res/drawable/bg_selector_tab_layout.xml
  app/src/main/res/drawable/bg_tab_selected.xml
  app/src/main/res/drawable/bg_tab_unselected.xml
  app/src/main/res/drawable/ic_icn_add_button_message.xml
  app/src/main/res/layout/activity_thunder_list.xml
  app/src/main/res/layout/fragment_home_dialog.xml
  app/src/main/res/layout/item_home_dialog.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/build.gradle.kts
  data/src/main/java/com/playtogether_android/data/api/sign/SignService.kt
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderCreateService.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderCreateMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSocialLogin.kt
  data/src/main/java/com/playtogether_android/data/model/request/thunder/RequestThunderCreate.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResSocialLogin.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResponseThunderCreate.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderCreateRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SocialLoginData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SocialLoginItem.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/PostThunderCreateData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderCreateRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/home/GetCrewListNameUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSocialLoginUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostMultipartThunderCreateUseCase.kt
Labels: 🛠Chore, 🍇종찬🍇

#189 Feat/183 onboarding modify code
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewEndOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/ResultWrapper.kt
  app/src/main/java/com/playtogether_android/app/util/SafeApiCall.kt
  app/src/main/res/layout/activity_on_boarding_introduce.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/api/onboarding/OnboardingService.kt
  data/src/main/java/com/playtogether_android/data/mapper/onboarding/OnBoardingMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/onboarding/RequestAddProfile.kt
  domain/src/main/java/com/playtogether_android/domain/model/network/ErrorBody.kt
  domain/src/main/java/com/playtogether_android/domain/model/onboarding/AddProfileData.kt
  domain/src/main/java/com/playtogether_android/domain/model/onboarding/AddProfileItem.kt
  domain/src/main/java/com/playtogether_android/domain/model/onboarding/NickNameDuplicationData.kt
Labels: 🌈Feature, 🍑혜빈🍑

#192 [FEAT] empty view 적용
  .gitignore
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideChatServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideHomeServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideLightServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideMessageServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideMyPageServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideOnboardingServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideRoomIdServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideSignServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideThunderCreateServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideThunderServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RetrofitModule_ProvideRetrofitObjectGsonFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RetrofitModule_ProvideRetrofitObjectMoshiFactory.java
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/res/drawable/rectangle_border_gray02_radius_10.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_thunder_do.xml
  app/src/main/res/layout/fragment_thunder_eat.xml
  app/src/main/res/layout/fragment_thunder_go.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🌈Feature, 🍇종찬🍇

#194 Feat/175 search
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideChatServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideHomeServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideLightServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideMessageServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideMyPageServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideOnboardingServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideRoomIdServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideSignServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideSubwayServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideThunderCreateServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/ApiModule_ProvideThunderServiceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideChatDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideHomeDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideLightDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideMessageDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideMyPageDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideOnBoardingDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideSignDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideSubwayDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideThunderCreateDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/DataSourceModule_ProvideThunderDataSourceFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/PlayTogetherApplication_GeneratedInjector.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideChatRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideHomeRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideLightRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideMessageRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideMyPageRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideOnBoardingRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideRoomIdRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideSignRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideSubwayRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideThunderCreateRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RepositoryModule_ProvideThunderRepositoryFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RetrofitModule_ProvideRetrofitObjectGsonFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/RetrofitModule_ProvideRetrofitObjectMoshiFactory.java
  app/build/generated/source/kapt/debug/com/playtogether_android/app/di/SerializationModule_ProvideMoshiFactory.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/ApiModule.kt
  app/src/main/java/com/playtogether_android/app/di/RepositoryModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/rectangle_border_gray02_fill_gray04_radius_21.xml
  app/src/main/res/drawable/rectangle_fill_black02_radius_21.xml
  app/src/main/res/drawable/selector_rectangle_gray04_to_black02.xml
  app/src/main/res/drawable/selector_text_gray02_to_white.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_thunder_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
  data/src/main/java/com/playtogether_android/data/api/search/SearchService.kt
  data/src/main/java/com/playtogether_android/data/model/response/search/SearchResult.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/search/SearchRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/search/SearchData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/search/SearchRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/search/GetSearchResultUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#196 [FEAT] 회원정보 입력
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/di/PlayTogetherApplication.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginTermsActivity.kt
  app/src/main/res/drawable/bg_black_white_radius_10.xml
  app/src/main/res/drawable/selector_gray01_main_green.xml
  app/src/main/res/layout/activity_login_info.xml
  app/src/main/res/layout/activity_login_terms.xml
  app/src/main/res/layout/dialog_only_year.xml
  app/src/main/res/layout/dialog_only_year_datepicker.xml
  app/src/main/res/layout/fragment_thunder_do.xml
  app/src/main/res/layout/fragment_thunder_eat.xml
  app/src/main/res/layout/fragment_thunder_go.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/com/playtogether_android/data/api/light/LightService.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/light/LightDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/light/LightRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
  domain/src/main/java/com/playtogether_android/domain/repository/light/LightRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetHotListUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/light/GetNewListUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#198 Fix/193 modify intent code
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewEndOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SelectOnboardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SignUpFinishActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignUpMainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_open_crew_end_on_boarding.xml
  app/src/main/res/layout/activity_search_subway.xml
  app/src/main/res/layout/activity_sign_up_finish.xml
  app/src/main/res/layout/activity_sign_up_info.xml
  app/src/main/res/layout/activity_sign_up_main.xml
  app/src/main/res/layout/dialog_one_question.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/api/onboarding/OnboardingService.kt
  data/src/main/java/com/playtogether_android/data/api/sign/SignService.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignId.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignUp.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResponseSignId.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResponseSignUp.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/IdDuplicationCheckData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/IdDuplicationCheckItem.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignUpData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SignUpItem.kt
  domain/src/main/java/com/playtogether_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignIdUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignInUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSignUpUseCaes.kt
Labels: 🐞Fix, 🍑혜빈🍑

#200 Fix/193 modify intent code
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_join_on_boarding.xml
  app/src/main/res/layout/activity_on_boarding_introduce.xml
  app/src/main/res/layout/activity_open_crew_on_boarding.xml
  app/src/main/res/layout/activity_search_subway.xml
  app/src/main/res/layout/activity_select_onboarding.xml
  build.gradle.kts
Labels: 🐞Fix, 🍑혜빈🍑

#201 Feat/199 setting mypage notion
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
Labels: 🌈Feature, 🍑혜빈🍑

#204 Feat/203 mypage setting quit view
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/ManageAccountActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageQuitActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/res/drawable/rectangle_border_red_radius_10dp.xml
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_my_page_quit.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: 🌈Feature, 🍑혜빈🍑

#209 Feat/208 mypage alarm setting
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_my_page_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍑혜빈🍑

#210 [FEAT] kakao login
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/di/PlayTogetherApplication.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginTermsActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  data/src/main/java/com/playtogether_android/data/api/sign/SignService.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/sign/SignDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/sign/SignMapper.kt
  data/src/main/java/com/playtogether_android/data/model/request/sign/RequestSignup.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResSocialLogin.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResTokenIssuance.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/sign/SignRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/IssuanceItem.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/SocialLoginData.kt
  domain/src/main/java/com/playtogether_android/domain/model/sign/UserInfo.kt
  domain/src/main/java/com/playtogether_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/sign/PostSocialLoginUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇
