Repository TEAM-PLAYTOGETHER/PlayTogether_Android, pull requests merged in 2022-09, with the labels that each got.

#213 [FEAT] 구글로그인 완
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/viewmodel/GoogleLoginRepository.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  data/src/main/java/com/playtogether_android/data/api/google_sign/GoogleService.kt
  data/src/main/java/com/playtogether_android/data/model/request/google/LoginGoogleRequestModel.kt
  data/src/main/java/com/playtogether_android/data/model/request/google/LoginGoogleResponseModel.kt
  data/src/main/java/com/playtogether_android/data/model/request/google/SendAccessTokenModel.kt
  data/src/main/java/com/playtogether_android/data/model/response/sign/ResLoginGoogle.kt
Labels: 🌈Feature, 🍇종찬🍇

#215 [CHORE] HEADER값 수정
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/di/ApiModule.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/AuthInterceptor.kt
  app/src/main/java/com/playtogether_android/app/util/ManageUtil.kt
  app/src/main/java/com/playtogether_android/app/util/PlayTogetherSharedPreference.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/playtogether_android/data/api/onboarding/OnboardingService.kt
Labels: 🛠Chore, 🍑혜빈🍑

#217 [FEAT] #212 - 회원탈퇴 서버통신 완료
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageQuitActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/viewModel/MyPageViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/MyInfoFragment.kt
  data/src/main/java/com/playtogether_android/data/api/mypage/MyPageService.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/mypage/MyPageDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/mypage/MyPageMapper.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/mypage/MyPageRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/repository/mypage/MyPageRepository.kt
Labels: 🌈Feature, 🍑혜빈🍑

#218 Fix/216 modify onboarding logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SelectOnboardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SignUpFinishActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/SignInActivity.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/res/layout/activity_sign_in.xml
  data/src/main/java/com/playtogether_android/data/mapper/onboarding/OnBoardingMapper.kt
  data/src/main/java/com/playtogether_android/data/model/response/mypage/ResponseUserDelete.kt
  data/src/main/java/com/playtogether_android/data/model/response/onboarding/ResponseRegisterCrew.kt
  domain/src/main/java/com/playtogether_android/domain/model/mypage/UserDeleteData.kt
  domain/src/main/java/com/playtogether_android/domain/model/onboarding/RegisterCrewData.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/mypage/DeleteUserUseCase.kt
Labels: 🐞Fix, 🍑혜빈🍑

#220 Feat/206 search server connect
  .idea/compiler.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/PlayTogetherSharedPreference.kt
  app/src/main/res/layout/activity_search.xml
  data/src/main/java/com/playtogether_android/data/api/search/SearchService.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/search/SearchRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/repository/search/SearchRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/search/GetSearchResultUseCase.kt
Labels: 🌈Feature, 🍏용민🍏

#224 [FIX] #219 - modify QA
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragmentDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginInfoActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginTermsActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SelectOnboardingActivity.kt
Labels: 🐞Fix, 🍑혜빈🍑

#226 [FEAT] 번개 상세뷰 이벤트
  app/src/main/java/com/playtogether_android/app/di/PlayTogetherApplication.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/PhotoDialog.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/drawable/img_popup.9.png
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/fragment_photo_dialog.xml
  app/src/main/res/layout/item_detail.xml
  app/src/main/res/values/arry.xml
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderChangeData.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderScrapData.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/GetThunderScrapUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostThunderReportUseCase.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostThunderScrapUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#228 [FIX] modify onboarding btn branch processing
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnBoardingIntroduceActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/res/layout/activity_on_boarding_introduce.xml
Labels: 🐞Fix, 🍑혜빈🍑

#229 [FEAT] 번개 상세뷰 다이어로그 추가
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialog.kt
  app/src/main/java/com/playtogether_android/app/util/CustomDialogSon.kt
  app/src/main/res/layout/dialog_check.xml
  app/src/main/res/values/arry.xml
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
Labels: 🌈Feature, 🍇종찬🍇

#232 [CHORE] 재다운로드뷰 crewId 전달
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageQuitActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
Labels: 🛠Chore, 🍑혜빈🍑

#233 Feat/227 searching view test
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_search_thunder_list.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/strings.xml
Labels: 🛠Chore, 🍏용민🍏

#235 [CHORE] 번개 상세뷰 분기처리, 로그아웃
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderAppliedActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/SplashActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/adapter/ThunderCategoryListItemAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/viewmodel/ThunderDetailViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/activity_thunder_list.xml
  app/src/main/res/layout/fragment_thunder_do.xml
  app/src/main/res/layout/fragment_thunder_eat.xml
  app/src/main/res/layout/fragment_thunder_go.xml
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/mapper/thunder/ThunderMapper.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderRepositoryImpl.kt
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/GetThunderExistCheck.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/GetThunderExistCheckerUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#237 Feat/219 add ga
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  data/src/main/java/com/playtogether_android/data/api/onboarding/SubwayInfoService.kt
Labels: 🐞Fix, 🍑혜빈🍑

#238 Feat/225 modify create thunder
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/values/strings.xml
Labels: 🌈Feature, 🍏용민🍏

#239 Feat/223 chatting socket
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChatAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/MessageFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/SendMessageSocket.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/SocketSingleton.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/SubscribeSocket.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/request/ReqEnterRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/request/ReqSendMessage.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/response/NewMessageReceived.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/response/ResConnection.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/response/ResEnterRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/response/ResExitRoom.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/data/response/ResSendMessage.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/ChatViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/viewmodel/MessageViewModel.kt
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/item_my_chat.xml
  app/src/main/res/layout/item_other_chat.xml
  data/src/main/java/com/playtogether_android/data/mapper/message/MessageMapper.kt
  domain/src/main/java/com/playtogether_android/domain/model/message/MessageData.kt
Labels: 🌈Feature, 🍏용민🍏

#241 [REFACTOR] 번개 생성뷰 null 처리, 번개 상세뷰 null된거 받아오기
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderViewModel.kt
  data/src/main/java/com/playtogether_android/data/api/thunder/ThunderCreateService.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSource.kt
  data/src/main/java/com/playtogether_android/data/datasource/thunder/ThunderCreateDataSourceImpl.kt
  data/src/main/java/com/playtogether_android/data/model/response/thunder/ResThunderDetailData.kt
  data/src/main/java/com/playtogether_android/data/repositoryimpl/thunder/ThunderCreateRepositoryImpl.kt
  domain/src/main/java/com/playtogether_android/domain/model/thunder/ThunderDetailData.kt
  domain/src/main/java/com/playtogether_android/domain/repository/thunder/ThunderCreateRepository.kt
  domain/src/main/java/com/playtogether_android/domain/usecase/thunder/PostMultipartThunderCreateUseCase.kt
Labels: 🌈Feature, 🍇종찬🍇

#253 Feat/223 chatting socket
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_icn_chat_active.xml
  app/src/main/res/drawable/ic_icn_chat_inactive.xml
  app/src/main/res/drawable/ic_icn_newmessage.xml
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_message_room.xml
  app/src/main/res/layout/item_my_chat.xml
  app/src/main/res/layout/item_other_chat.xml
  app/src/main/res/values/strings.xml
Labels: 🐞Fix, 🍏용민🍏

#257 [CHORE] CRYINGCRYING_QA
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeHotAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/adapter/HomeNewAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/LoginActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/login/view/LoginTermsActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/mypage/MyPageSettingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/ApplicantListAdapter.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/viewmodel/ThunderListViewModel.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/viewmodel/UserInfoViewModel.kt
  app/src/main/java/com/playtogether_android/app/util/ViewExt.kt
  app/src/main/res/layout/activity_create_thunder.xml
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_tab_apply.xml
  app/src/main/res/layout/fragment_tab_like.xml
  app/src/main/res/layout/fragment_tab_open.xml
  app/src/main/res/layout/item_home_hot.xml
  app/src/main/res/layout/item_home_new.xml
  app/src/main/res/layout/item_thunder_list.xml
  app/src/main/res/values/strings.xml
Labels: 🛠Chore, 🍇종찬🍇

#258 [CHORE] crying QA part 2
  app/src/main/java/com/playtogether_android/app/presentation/ui/createThunder/CreateThunderActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/ThunderDetailActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/JoinOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OnboardingReDownLoadActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/OpenCrewEndOnBoardingActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderDoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderEatFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderGoFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/thunder/list/view/ThunderListActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/viewmodel/UserInfoViewModel.kt
  app/src/main/res/layout/activity_thunder_detail.xml
  app/src/main/res/layout/fragment_photo_dialog.xml
  app/src/main/res/layout/item_thunder_applicant_list.xml
  data/src/main/java/com/playtogether_android/data/singleton/PlayTogetherRepository.kt
Labels: 🛠Chore, 🍇종찬🍇

#261 Feat/259 modify myinfo
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/onboarding/SearchSubwayActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/EditProfileActivity.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/userInfo/MyInfoFragment.kt
  app/src/main/res/layout/activity_search_subway.xml
Labels: 🌈Feature, 🍑혜빈🍑

#263 Feat/fcm messaging
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/playtogether_android/app/presentation/ui/home/view/HomeFragment.kt
  app/src/main/java/com/playtogether_android/app/presentation/ui/message/ChattingActivity.kt
  app/src/main/java/com/playtogether_android/app/util/FirebaseMessagingServiceUtil.kt
  app/src/main/java/com/playtogether_android/app/util/MyFirebaseMessagingService.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 🌈Feature, 🐞Fix, 🍏용민🍏
